name: Estanplaza Eventos

include: 
  - fonts
  - javascript

exclude:
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock  
  - gulpfile.js
  - node_modules


collections:
  places:
    output: true
    permalink: /places/:path/