name: Estanplaza Eventos

source              : ./src
destination         : ./_site

include: 
  - fonts

exclude:
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock  
  - gulpfile.js
  - node_modules


sass:
  sass_dir: /_scss
  style: compressed

collections:
  places:
    output: true
    permalink: /places/:path/

slides:
  - img_url: images/slide1.jpg
  - img_url: images/slide2.jpg
  - img_url: images/slide3.jpg
  - img_url: images/slide4.jpg
  - img_url: images/slide5.jpg

menu-items:
- name: home
  id: home
- name: about us
  id: about
- name: places
  id: places-menu 
  subitems:
    - name: forests
      url: /places/forest
    - name: jungles
      url: /places/jungle
    - name: mountains
      url: /places/mountain
    - name: tropical forests
      url: /places/tropical-forest
    - name: valleys
      url: /places/valley
- name: benefits
  id: benefits
- name: testimonials
  id: testimonials
- name: contact
  id: contact